### ISSUE TITLE
slow-gc gives I/O alert highlighting CPU graph, even before heap limit change

### ISSUE THREAD

**Issue by AlanSl** [nearform/node-clinic-doctor-examples#13]
Running Doctor on `slow-gc` gives a I/O alert and flags the CPU graph (expected a Garbage Collection alert flagging the Memory graph).

Strange thing is, it's not just Doctor after 3.9.0, [Do not issue the GC category if the heap is smaller than 128MB. (#213)](https://github.com/nearform/node-clinic-doctor/pull/213).

Using `clinic doctor --autocannon [/] -- node slow-gc` on the following:

Doctor v3.8.1 (last release before the above):

- Mac, Node v11.3.0 - **I/O alert** - https://upload.clinicjs.org/public/6853562abc182b6077e86c0cc655049e035bcc7e6bd188005416386365fdd7f7/28353.clinic-doctor.html
- Mac, Node v10.14.1 - **I/O alert** - https://upload.clinicjs.org/public/c692a2d8377df75c650d3ff3acafe9503bbab5660cc307961404c727c1477d5e/31260.clinic-doctor.html
- Mac, Node v10.9.0 - **I/O alert** - https://upload.clinicjs.org/public/4e089ec2c323f0514ae2002b1a54ddf8809bc1d3da896b78358b20fcc2f9d100/28486.clinic-doctor.html
- Mac, Node v8.12.0 - **I/O alert** - https://upload.clinicjs.org/public/04874a62c9bab91d34ded7c42b3d692f1012894b3c3373555de5f0157eb5acbd/29988.clinic-doctor.html

**Comment by AlanSl** [comment]
Similar results on Windows too, and Doctor 3.4.0 (though there's some dependency flakiness going back that far)

Doctor v3.11.0 (latest release):

- Mac, Node v11.3.0 - **I/O alert** - https://upload.clinicjs.org/public/98fb0a641143a8ba26a025453e3cf5c2b340735e67b29570e7434ea6a77e9469/31420.clinic-doctor.html
- Mac, Node v10.14.1 - **I/O alert** - https://upload.clinicjs.org/public/8f1772ae9caa7649bb47b447b8d804abb11217c88e64ce336430e87e1b45b9c5/31296.clinic-doctor.html
- Mac, Node v10.9.0 - **I/O alert** - 
https://upload.clinicjs.org/public/51ff37c806eea8044d64d93dcbe85b2efe1be4529b8576cf061d3d92a7bcf711/31597.clinic-doctor.html
- Mac, Node v8.12.0 - **I/O alert** - 
https://upload.clinicjs.org/public/2c01d45689934c1441cdc96e8c105230d642b128e3e503ee5238257b4890adef/31718.clinic-doctor.html

**Comment by AndreasMadsen** [comment]
You need to run with `clinic doctor --autocannon [ -c 2500 / ] -- node slow-gc` as documented in the readme.
